import Head from 'next/head';
import {useState} from 'react'
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
	AiFillTwitterCircle,
	AiFillLinkedin,
	AiFillInstagram,
} from 'react-icons/ai';
import {motion} from 'framer-motion'
import Image from 'next/image';
import pamz3 from '../../public/pamz2-modified.png';
import react from '../../public/react-img.png';
import tailwind from '../../public/tailwind-img.png';
import fmotion from '../../public/motion-img.png';
import js from '../../public/js-removebg-preview.png';
import css from '../../public/css.png';
import menu from '../../public/menu.png';
import loop from '../../public/loopstudios.png';
import review from '../../public/reviews.png';
import todo from '../../public/todo.png';
import login from '../../public/login.png';
import pv1 from '../../public/pv1.png';
import assutech from '../../public/assutech.png';

export default function Home() {
  const [darkMode, setDarkMode] = useState(true)

	return (
		<div className={darkMode ? 'dark' : ''}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
				<section className='min-h-screen'>
					<nav className='py-10 flex justify-between items-center'>
						<h1 className='text-xl font-burtons dark:text-white'>
							developedbyamat
						</h1>
						<ul className='flex items-center'>
							<li>
								<BsFillMoonStarsFill
									onClick={() => setDarkMode(!darkMode)}
									className='text-2xl cursor-pointer dark:text-white'
								/>
							</li>
							<li>
								<a
									href='#'
									className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'
								>
									Projects
								</a>
							</li>
						</ul>
					</nav>
					<div className='text-center p-10'>
						<h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl '>
							Pa Amat Jow
						</h2>
						<h3 className='text-2xl py-2 md:text-3xl dark:text-white'>
							Frontend Developer.
						</h3>
						<p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-300'>
							Hi, I am a frontend enthusiast who aspires to become a fullstack
							developer.
						</p>
					</div>
					<div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400'>
						<a href='#'>
							<AiFillTwitterCircle />
						</a>
						<a href='#'>
							<AiFillLinkedin />
						</a>
						<a href='#'>
							<AiFillInstagram />
						</a>
					</div>
					<div className='relative mt-20 mx-auto bg-gradient-to-b from-teal-300 rounded-full w-80 h-80 overflow-hidden md:w-96 md:h-96 dark:from-teal-500'>
						<Image
							src={pamz3}
							alt='Pa Amat'
							className='absolute bottom-0 left-0 right-4 mx-auto w-[295px] h-[370px] md:w-[320px] md:h-[430px]'
						/>
					</div>
				</section>
				{/* technologies */}
				<section className='py-16'>
					<div className='text-center '>
						<h3 className='text-2xl md:text-3xl py-2 my-2 dark:text-white'>
							Technologies I work with
						</h3>
						<div className='border-b-2 border-teal-500 w-[10rem] mx-auto'></div>
						{/* <p className='text-md md:text-xl max-w-xl mx-auto py-2 leading-8 text-gray-800 my-2 dark:text-gray-300'>
							I spend most of my free time building projects to increase my
							knowledge in these technologies.
						</p> */}
					</div>
					<div className='flex flex-wrap gap-8 justify-center mx-auto max-w-[900px] my-8 dark:text-white '>
						<div className='flex flex-col space-y-2 items-center w-36 py-2 rounded-lg shadow-md shadow-teal-500/50 dark:bg-gray-700'>
							<div className='relative w-[80px] h-[80px] md:w-[100px] md:h-[100px]'>
								<Image src={react} fill objectFit='cover' alt='react' />
							</div>
							<h3 className='text-lg'>React</h3>
						</div>
						<div className='flex flex-col space-y-2 items-center w-36 py-2 rounded-lg shadow-md shadow-teal-500/50 dark:bg-gray-700'>
							<div className='relative w-[80px] h-[80px] md:w-[100px] md:h-[100px]'>
								<Image src={tailwind} fill objectFit='cover' alt='react' />
							</div>
							<h3 className='text-lg'>Tailwind</h3>
						</div>
						<div className='flex flex-col space-y-2 items-center w-36 py-2 rounded-lg shadow-md shadow-teal-500/50 dark:bg-gray-700'>
							<div className='relative w-[80px] h-[80px] md:w-[100px] md:h-[100px]'>
								<Image src={fmotion} fill objectFit='cover' alt='react' />
							</div>
							<h3 className='text-lg'>Framer Motion</h3>
						</div>
						<div className='flex flex-col space-y-2 items-center w-36 py-2 rounded-lg shadow-md shadow-teal-500/50 dark:bg-gray-700'>
							<div className='relative w-[80px] h-[80px] md:w-[100px] md:h-[100px]'>
								<Image src={js} fill objectFit='cover' alt='react' />
							</div>
							<h3 className='text-lg'>ES6+</h3>
						</div>
						<div className='flex flex-col space-y-2 items-center w-36 py-2 rounded-lg shadow-md shadow-teal-500/50 dark:bg-gray-700'>
							<div className='relative w-[80px] h-[80px] md:w-[100px] md:h-[100px]'>
								<Image src={css} fill objectFit='cover' alt='react' />
							</div>
							<h3 className='text-lg'>CSS</h3>
						</div>
					</div>
				</section>
				{/* projects */}
				<section className='py-16'>
					<div className='text-center'>
						<h3 className='text-2xl md:text-3xl py-2 my-2 dark:text-white'>
							Projects
						</h3>
						<div className='border-b-2 border-teal-500 w-[10rem] mx-auto'></div>
						<p className='text-md md:text-xl max-w-xl mx-auto py-2 leading-8 text-gray-800 my-2 dark:text-gray-300'>
							I spend most of my free time building projects to better my
							understanding in the concepts I have learned.
						</p>
					</div>
					<div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
						<div className='basis-1/3 flex-1'>
							<Image
								src={assutech}
								className='rounded-lg object-cover w-full h-full'
								alt=''
								
							/>
						</div>
						<div className='basis-1/3 flex-1'>
							<Image
								src={menu}
								className='rounded-lg object-cover w-full h-full'
								alt=''
								
							/>
						</div>
						<div className='basis-1/3 flex-1'>
							<Image
								src={review}
								className='rounded-lg object-cover w-full h-full'
								alt=''
								
							/>
						</div>
						<div className='basis-1/3 flex-1'>
							<Image
								src={loop}
								className='rounded-lg object-cover w-full h-full'
								alt=''
								
							/>
						</div>
						<div className='basis-1/3 flex-1'>
							<Image
								src={todo}
								className='rounded-lg object-cover w-full h-full'
								alt=''
								
							/>
						</div>
					</div>
				</section>
			</main>
		</div>
	);
}
